<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>OONI Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="FullAnalysis_JN_files/libs/clipboard/clipboard.min.js"></script>
<script src="FullAnalysis_JN_files/libs/quarto-html/quarto.js"></script>
<script src="FullAnalysis_JN_files/libs/quarto-html/popper.min.js"></script>
<script src="FullAnalysis_JN_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FullAnalysis_JN_files/libs/quarto-html/anchor.min.js"></script>
<link href="FullAnalysis_JN_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FullAnalysis_JN_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FullAnalysis_JN_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FullAnalysis_JN_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FullAnalysis_JN_files/libs/bootstrap/bootstrap-880bef1195e03ea8ec6c5b514ed46a42.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">OONI Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="ef12e16f-8b96-41c2-a2cb-8ead5ac7aa8d" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic Imports</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> urllib.parse <span class="im">import</span> urlparse</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Imports</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># sklearn</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn <span class="im">import</span> metrics</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> KMeans</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> IsolationForest</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Statstools</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> proportions_ztest</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.weightstats <span class="im">import</span> ztest <span class="im">as</span> ztest</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.seasonal <span class="im">import</span> seasonal_decompose</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="d92552c4-fe5b-4968-bcdf-a9f513451718" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot configuration</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'darkgrid'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>sns.set_palette(<span class="st">'tab10'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> sns.color_palette()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="a2d39374-e3cb-4c25-80aa-654e982b311b" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data paths</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>base_dir <span class="op">=</span> <span class="st">'../../Data/'</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>hr_dir <span class="op">=</span> os.path.join(base_dir, <span class="st">'HR'</span>, <span class="st">'processed'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>hr_years <span class="op">=</span> [<span class="st">'2021'</span>, <span class="st">'2022'</span>, <span class="st">'2023'</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>np_dir <span class="op">=</span> os.path.join(base_dir, <span class="st">'NP'</span>, <span class="st">'processed'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>np_years <span class="op">=</span> [<span class="st">'2022'</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>by_dir <span class="op">=</span> os.path.join(base_dir, <span class="st">'BY'</span>, <span class="st">'processed'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>by_years <span class="op">=</span> [<span class="st">'2022'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1 Introduction</h2>
<p>For our project, we decided we wanted to study an learn more about censorship worldwide. In today’s world, censorship is becoming more and more common. Many countries censor their political opponents, or censor criticism of themselves. We want to help combat this. Our project aims to do some small but significant work to help create a more open and free world.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>Our dataset was created by the Open Observatory of Network Interference (OONI), a non-profit organization based in Italy focused on fighting internet censorship worldwide. The project was originally founded by The Tor Project, but now most of its funding comes from donations.</p>
<p>The dataset comes from the OONI Probe, a mobile app launched by OONI in 2017. At the time, it collected the largest dataset on internet censorship ever recorded. To this day, it remains the largest publicly available dataset on the topic. The app runs in the background on any phone that has it installed. OONI organizes coordinated tests, where phones in a specific region perform tests at the same time. These phones send internet requests to various sources, and the responses are reported back to a server at OONI’s headquarters. This process provides a broad overview of internet connectivity in regions with OONI app users. Researchers can analyze the data to identify sites and services that are consistently blocked, or use models to detect significant changes in internet access.</p>
<p>When sites are temporarily blocked, often due to political reasons, this is referred to as “temporal blocking.” We chose this dataset to analyze after reading a paper (https://www.ndss-symposium.org/ndss-paper/modeling-and-detecting-internet-censorship-events/) that identified instances of temporal blocking in Nepal in 2022. Temporal blocking is a major challenge facing the free world. Smaller, and less indistrialized nations often get away with temporal blocking of political content around elections. Our goal for this project revolves around characterizing temporal censorship events.</p>
<p>The OONI probe performs at least 17 different types of tests. We won’t go over all of them here, but we decided to focus on the web connectivity tests due to the large amount of data, and ease of interpretation. These tests first send out a DNS request for the targeted domain, and report if the DNS request returned as expected. If so, they then send out an HTTPS request to the domain, and record the response. This gives a broad view of whether citizens in a specific region are able to access content that OONI deems important or controversial. A control connection is also sent out at the same time called a “test helper”. The responses of the test helper, and the tests are compared to create the final data point.</p>
<p>The web connectivity tests are massive. We started by trying to download certain chunks of data, and discovered that the data for the United States for one month was over 140 GB. The entire OONI database is several terabytes of data. We instead decided to focus on specific regions during the similar timeframes to perform our analysis. By narrowing our scope, we believe that we can do better work for this project. Due to the paper that we read, we started with Nepal 2022. We decided to analyze two other countries during the same timeframe, to use as points of comparison: Croatia and Belarus. We were looking for other small countries, and we wanted two countries on opposite sides of the censorship spectrum. Belarus is a well known censored country, and Croatia’s constitution bans any form of internet censorship, thus they seemed like a perfect choice. Due to some issues with the dataset that we will discuss later, we ended up pivoting to focus on Croatia, and thus downloaded the Croatia 2021 and 2023 datasets as well to supplement our study.</p>
<div id="10ed9fd7-4945-4f76-be58-9be8c1c66d22" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load all datasets</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>web_data <span class="op">=</span> {</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'hr'</span> : {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        year : pd.read_csv(os.path.join(hr_dir, year, <span class="st">'webconnectivity.csv'</span>)) <span class="cf">for</span> year <span class="kw">in</span> hr_years</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'np'</span> : {</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        year : pd.read_csv(os.path.join(np_dir, year, <span class="st">'webconnectivity.csv'</span>)) <span class="cf">for</span> year <span class="kw">in</span> np_years</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'by'</span> : {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        year : pd.read_csv(os.path.join(by_dir, year, <span class="st">'webconnectivity.csv'</span>)) <span class="cf">for</span> year <span class="kw">in</span> by_years</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize URLs</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> url_standardize(url):</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    parsed <span class="op">=</span> urlparse(url)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> parsed.netloc.split(<span class="st">'.'</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> <span class="st">'.'</span>.join(b[<span class="bu">len</span>(b)<span class="op">-</span><span class="dv">2</span>:])  <span class="co"># Remove any www</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> parsed.path <span class="cf">if</span> parsed.path <span class="op">==</span> <span class="st">""</span> <span class="kw">or</span> parsed.path[<span class="op">-</span><span class="dv">1</span>] <span class="op">!=</span> <span class="st">"/"</span> <span class="cf">else</span> parsed.path[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> c <span class="op">+</span> d</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all datasets and clean</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> country <span class="kw">in</span> web_data:</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> web_data[country]:</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        wd <span class="op">=</span> web_data[country][year]</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        wd[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(wd[<span class="st">'date'</span>])</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        wd <span class="op">=</span> wd.set_index(<span class="st">'date'</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>        wd[<span class="st">'input'</span>] <span class="op">=</span> wd[<span class="st">'input'</span>].<span class="bu">map</span>(url_standardize)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>        web_data[country][year] <span class="op">=</span> wd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The structure of the data is as follows. There are 18 different fields in the dataset:</p>
<ul>
<li>Date - when the test occured</li>
<li>Probe_asn - what network the test occured in, using the unique Autonomous System number</li>
<li>Status_code_match - whether the HTTPS status code matches between the test and control</li>
<li>Resolver_asn - what network the DNS resolver contacted is located in</li>
<li>X_null_null_flags - unused</li>
<li>Body_length_match - whether the length of the response body match between the test and control</li>
<li>DNS_consistency - whether the DNS resolution is consistent between the test and control</li>
<li>Headers_match - whether the final response headers match between the test and control</li>
<li>DNS_experiment_failure - describes the specific failures of any DNS request</li>
<li>HTTP_experiment_failure - describes the specific failures of any HTTP request</li>
<li>Body_proportion - The ratio of body lengths between the control and test response</li>
<li>Title_match - whether the final response title matches between the test and control</li>
<li>Blocking - says whether the domain has been judged to be blocked or not by OONI’s algorithm</li>
<li>Accessible - whether or not the final response was able to reach the requested domain</li>
<li>X_dns_flags - unused</li>
<li>Control_failure - describes the specific failures of any control request</li>
<li>X_blocking_flags - unused</li>
<li>input - the domain the test wanted to connect to</li>
</ul>
<p>Example data (Nepal 2022):</p>
<div id="2f470cee-74a9-4cf8-ab74-0d8bf486a020" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show some example data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>web_data[<span class="st">'np'</span>][<span class="st">'2022'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">probe_asn</th>
<th data-quarto-table-cell-role="th">http_experiment_failure</th>
<th data-quarto-table-cell-role="th">x_dns_flags</th>
<th data-quarto-table-cell-role="th">status_code_match</th>
<th data-quarto-table-cell-role="th">resolver_asn</th>
<th data-quarto-table-cell-role="th">headers_match</th>
<th data-quarto-table-cell-role="th">blocking</th>
<th data-quarto-table-cell-role="th">body_length_match</th>
<th data-quarto-table-cell-role="th">input</th>
<th data-quarto-table-cell-role="th">control_failure</th>
<th data-quarto-table-cell-role="th">title_match</th>
<th data-quarto-table-cell-role="th">accessible</th>
<th data-quarto-table-cell-role="th">x_null_null_flags</th>
<th data-quarto-table-cell-role="th">x_blocking_flags</th>
<th data-quarto-table-cell-role="th">body_proportion</th>
<th data-quarto-table-cell-role="th">dns_consistency</th>
<th data-quarto-table-cell-role="th">dns_experiment_failure</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-01-02</td>
<td>AS17501</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS17501</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>fteproxy.org</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-01-02</td>
<td>AS17501</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS17501</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>sbc.net</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-01-02</td>
<td>AS17501</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS17501</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>ecequality.org</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>inconsistent</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-01-02</td>
<td>AS17501</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS17501</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>episcopalchurch.org</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-01-02</td>
<td>AS17501</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS17501</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>icrw.org</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>0.999723</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-12-31</td>
<td>AS23752</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS23752</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>facebook.com</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>0.975015</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-12-31</td>
<td>AS23752</td>
<td>NaN</td>
<td>NaN</td>
<td>False</td>
<td>AS23752</td>
<td>True</td>
<td>False</td>
<td>NaN</td>
<td>instagram.com</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-12-31</td>
<td>AS23752</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS23752</td>
<td>True</td>
<td>False</td>
<td>NaN</td>
<td>youtube.com</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2022-12-31</td>
<td>AS23752</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS23752</td>
<td>True</td>
<td>False</td>
<td>NaN</td>
<td>twitter.com</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2022-12-31</td>
<td>AS23752</td>
<td>NaN</td>
<td>NaN</td>
<td>True</td>
<td>AS23752</td>
<td>True</td>
<td>False</td>
<td>True</td>
<td>valence.community</td>
<td>NaN</td>
<td>True</td>
<td>True</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>consistent</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>69444 rows × 17 columns</p>
</div>
</div>
</div>
<p>Of these fields, we care about 3 of them for our analysis: <code>date</code>, <code>input</code>, and <code>blocking</code>. Luckily for us, the <code>blocking</code> field already does all of the preprocessing we would need to detect blocking events. This field analyzes each of the other fields to tell us whether or not blocking has occurred, and what type of blocking the heuristics believe has occurred. The possible values are as follows:</p>
<div id="7d5f74d0-f157-45ee-ad99-6508356b2a63" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show unique test types</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>event_types_disp <span class="op">=</span> pd.Series(web_data[<span class="st">'hr'</span>][<span class="st">'2022'</span>][<span class="st">'blocking'</span>].sort_values().unique())</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(event_types_disp, columns<span class="op">=</span>[<span class="st">'Blocking Type'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Blocking Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>dns</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>http-diff</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>http-failure</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>tcp_ip</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>These specific blocking test responses are:</p>
<ul>
<li><code>False</code> - No blocking methods were detected
<ul>
<li>Either the site is accessible, or the site is inaccesible to both the test and control groups.</li>
</ul></li>
<li><code>NaN</code> - The results of the test were inconclusive, and thus should be discarded
<ul>
<li>We ignore these in our visualization, and model creation.</li>
</ul></li>
<li><code>dns</code> - The DNS server does not resolve the site properly, aka the DNS resolution differed between test and control
<ul>
<li>DNS is a service for translating domains to an IP address. It is the first step in any web access. It is commonly used as the first line of censorship. Groups will return a false IP address, or DNS error to implement censorship.</li>
</ul></li>
<li><code>httpdiff</code> - The HTTP response differs between test and control.
<ul>
<li>This blocking type means that the request returned a block page to the user. The censoring group will analyze the destination IP address, or packet contents, and return a block page to deter the user from continuing to access this source.</li>
</ul></li>
<li><code>httpfail</code> - The HTTP response returns with a failure error code, while the control does not
<ul>
<li>This blocking type means that the blocking entity intercepted the packet exactly as in the httpdiff failure, but instead of returning a block page returned an HTTP failure response code.</li>
</ul></li>
<li><code>tcp</code> - The response returned with the TCP RST flag set to 1
<ul>
<li>This flag is supposed to be set when a failure occurs forcing all communication to halt. Censoring groups will use the flag to falsely force the machine to block, giving the view of a network failure to the user. The blocking entity intercepted the packet the same as the last 2 blocking types, but implements the response differently.</li>
</ul></li>
</ul>
<p>Most censored networks will use a mixture of all 4 blocking types to implement their censorship (dns, httpdiff, httpfail, tcp). A single event of any type does not necessarily mean blocking, but a large number of events in a similar timeframe likely mean blocking. Normally under 5% of events being blocked are not cause for concern.</p>
<p>So to recap, our dataset is the OONI censorship dataset for Croatia 2021-2023, Belarus for 2022, and Nepal for 2022. We are analyzing the blocking patterns during that time frame as a time series. We believe we can use this data to figure out more about temporal censorship in the world. But what specific questions do we want to answer?</p>
</section>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<p>In our initial proposal, we set out a group of lofty goals to detect worldwide censorship. As we explored the data, and discovered its size, we decided to pivot. We wanted to narrow our scope, and discover more about specific regions of the world. We decided to analyze Nepal, Croatia, and Belarus as stated. We wanted to answer these 6 questions about at least 1 country. We eventually decided on these questions for Croatia specifically.</p>
<hr>
<ol type="1">
<li><p>What years of data have anomalies worth spending time on?</p></li>
<li><p>What date ranges are truly anomalous within our dataset?</p></li>
<li><p>What is happening inside of our anomalous date ranges?</p></li>
<li><p>What is being blocked in these date ranges, that is not outside of the ranges?</p></li>
<li><p>Are these differences statistically significant?</p></li>
<li><p>How do the different countries compare to each other in terms of blocking events?</p></li>
</ol>
<p>We believe that these questions are significant, and worth our time.</p>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<p><em>An essential part of data science is visualization, to understand the data. R makes some of this easy, through powerful plotting tools. You can easily view scatterplots of all pairs of variables with the pairs function, you can generate plots or histograms for individual variables, and many more complex visualizations are available in other R packages. ggplot2 is particularly powerful. 1</em> You can learn more R techniques for manipulating, visualizing, and presenting data in the free book “R for Data Science” (https://r4ds.had.co.nz/).</p>
<p>To start our data exploration phase, we made a series of simple graphs showing the blocking events throughout time during 2022.</p>
<p>The first graph shows the fraction of total events in each blocking class over time. The x axis is time, and the y axis is the proportion of events that came back with each class. It is a stackplot, which helps us view the total blocking events for a time period. The plot uses a 7 day rolling window to smooth out the plot, while still giving us the important trends. The legend shows which colors apply to which blocking event type. We are not using the NaN blocking events, as they are inconclusive, and usually are the result of a glitch with OONI’s system. We can use this to see how total events change over time.</p>
<p>The second graph shows similar information, but in a different way. This graph shows the same time proportions as above, but not as a stackplot. This plot helps us see how the events proportionality relates to each other.</p>
<div id="7a4cea91" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>event_types <span class="op">=</span> pd.Series(web_data[<span class="st">'hr'</span>][<span class="st">'2022'</span>][<span class="st">'blocking'</span>].dropna().sort_values().unique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="385afe78-3b14-4408-be05-1e944c78b4f7" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data into specific blocking methods</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>blocking_events <span class="op">=</span> {</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    country : {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        year : {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>            event_type: web_data[country][year][web_data[country][year][<span class="st">'blocking'</span>] <span class="op">==</span> event_type]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> event_type <span class="kw">in</span> event_types</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        } <span class="cf">for</span> year <span class="kw">in</span> web_data[country]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">for</span> country <span class="kw">in</span> web_data</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="f1def090-4c78-4e09-8812-aa1d5e63fd6b" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute rolling totals, means, and standard deviations</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>k<span class="op">=</span><span class="dv">7</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>totals <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>means <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>stds <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>quarts <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>quants <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> country <span class="kw">in</span> blocking_events:</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country]:</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> event_type <span class="kw">in</span> blocking_events[country][year]:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Calculate date range</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>            date_range <span class="op">=</span> pd.date_range(start<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">-01-01'</span>, end<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">-12-31'</span>, freq<span class="op">=</span><span class="st">'D'</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Fill all empty events with zeroes</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>            d <span class="op">=</span> blocking_events[country][year][event_type]</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            tmp <span class="op">=</span> d.groupby(d.index).size()</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>            totals[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).<span class="bu">sum</span>().dropna()</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>            means[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().dropna()</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>            stds[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).std().dropna()</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>            quarts[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().quantile([<span class="fl">0.25</span>, <span class="fl">0.75</span>]).dropna()</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>            quants[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().quantile([<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="fl">0.99</span>]).dropna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="a8dbe21b-146c-45f9-bc65-72939d489249" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate fractional events</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fracs <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> totals[country] } <span class="cf">for</span> country <span class="kw">in</span> totals}</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> country <span class="kw">in</span> totals:</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> totals[country]:</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Calculate fractional of all possible events</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        d <span class="op">=</span> pd.DataFrame(totals[country][year])</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        tsum <span class="op">=</span> d.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        fracs[country][year] <span class="op">=</span>  d.div(tsum, axis<span class="op">=</span><span class="dv">0</span>).fillna(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="14406b5c" class="cell" data-execution_count="44">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_basic_visualization(country, year):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select a country and year</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> fracs[country][year]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> f[f.columns[f.columns <span class="op">!=</span> <span class="st">'False'</span>]]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    ft <span class="op">=</span> [f[c] <span class="cf">for</span> c <span class="kw">in</span> f.columns.sort_values()]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    temp_country <span class="op">=</span> <span class="st">""</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> country <span class="op">==</span> <span class="st">"np"</span>:</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        temp_country <span class="op">=</span> <span class="st">"Nepal"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> country <span class="op">==</span> <span class="st">"by"</span>:</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        temp_country <span class="op">=</span> <span class="st">"Belarus"</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> country <span class="op">==</span> <span class="st">"hr"</span>:</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        temp_country <span class="op">=</span> <span class="st">"Croatia"</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plot fractional events</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">20</span>, <span class="dv">10</span>]</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    plt.figure()</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    plt.stackplot(ft[<span class="dv">0</span>].index, <span class="op">*</span>ft, labels<span class="op">=</span>f.columns.sort_values(), alpha<span class="op">=</span><span class="fl">0.65</span>)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    plt.grid()</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Fractional Blocking Events For </span><span class="sc">{</span>temp_country<span class="sc">}</span><span class="ss"> in </span><span class="sc">{</span>year<span class="sc">}</span><span class="ss"> Over Time (k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">20</span>, <span class="dv">10</span>]</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    plt.figure()</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    plt.plot(f, label<span class="op">=</span>f.columns)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>    plt.grid()</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Mean and Standard Deviations of Blocking Events For </span><span class="sc">{</span>temp_country<span class="sc">}</span><span class="ss"> in </span><span class="sc">{</span>year<span class="sc">}</span><span class="ss"> (k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">)'</span>)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="nepal-2022" class="level5">
<h5 class="anchored" data-anchor-id="nepal-2022">Nepal 2022</h5>
<hr>
<div id="ab72ac49-a8b6-4740-840a-c13771db0c83" class="cell" data-execution_count="45">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>make_basic_visualization(<span class="st">"np"</span>, <span class="st">"2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-13-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From this data, we see some interesting trends. The Nepal data is inconsistent. There are some obvious spikes, and some obvious valleys, but they don’t tell us the whole story. There’s some periods of time which don’t have data. There are several weeks at a time which have no data. This makes analyzing this dataset difficult. There are also large gaps in the data even during the ful time. During the first several months, most data is nearly a week apart from each other. This hurts the readability of the data even more. There appears to be some level of censorship going on in the early months (which is when it was reported to happen), but the gaps make definitive conclusions impossible. Due to these gaps, we decided to look at our other countries/years for our analysis.</p>
</section>
<section id="belarus-2022" class="level5">
<h5 class="anchored" data-anchor-id="belarus-2022">Belarus 2022</h5>
<div id="4d5f11b2-fd6d-4051-b1b2-b95132a48910" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>make_basic_visualization(<span class="st">"by"</span>, <span class="st">"2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Belarusian data gives us more of what we expect to see in a dataset. There is consistent data throughout the entire timeframe, making this a more useful dataset to analyze. Compared to Nepal, there is no periods of time without data. With Nepal, even periods with data had gaps of several days. Belarus is more consistent, thus we can do more analysis on these graphs.</p>
<p>Belarus is a country widely known for restrictions on the flow of information, so we predicted it to be fairly censored. The data was actually less censored than we expected it to be. Normally, around 7-8% of Belarus tests come back with a failure. This number does climb up all the way to nearly 17% during the end of year spike. This difference may have something to do with the Russian invasion of Ukraine, but this is not the main focus of our investigation.</p>
<p>In Belarus, the majority of day-to-day censorship appears to be httpfailure type events, meaning Belarus primarily responds to packets by sending back an HTTP failure code. There are also large spikes of DNS failures, and httpdiff failures, but tcp errors do appear to be stable and low. This gives us some idea of the preffered methods of censorship by the Belarusian government.</p>
<p>Overall, this is an interesting dataset to analyze, but we ended up not using it as our primary analysis. Belarus is a known restricted country, and showing that is not new information. The Belarusian data makes for a good point of comparison, but it is not the primary focus of this analysis.</p>
</section>
<section id="croatia-2022" class="level5">
<h5 class="anchored" data-anchor-id="croatia-2022">Croatia 2022</h5>
<div id="18739458" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>make_basic_visualization(<span class="st">"hr"</span>, <span class="st">"2022"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="48fcb19a" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>start_date <span class="op">=</span> <span class="st">'2022-03-24'</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>end_date <span class="op">=</span> <span class="st">'2022-04-18'</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> fracs[<span class="st">"hr"</span>][<span class="st">"2022"</span>]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>f.index <span class="op">=</span> pd.to_datetime(f.index)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> f[f.columns[f.columns <span class="op">!=</span> <span class="st">'False'</span>]]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> f[(f.index <span class="op">&gt;=</span> start_date) <span class="op">&amp;</span> (f.index <span class="op">&lt;=</span> end_date)]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ft <span class="op">=</span> [f[c] <span class="cf">for</span> c <span class="kw">in</span> f.columns.sort_values()]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot fractional events</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">20</span>, <span class="dv">10</span>]</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>plt.stackplot(ft[<span class="dv">0</span>].index, <span class="op">*</span>ft, labels<span class="op">=</span>f.columns.sort_values(), alpha<span class="op">=</span><span class="fl">0.65</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f'Fractional Blocking Events For Croatia in </span><span class="sc">{</span>year<span class="sc">}</span><span class="ss"> Over Time (k=</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Text(0.5, 1.0, 'Fractional Blocking Events For Croatia in 2022 Over Time (k=7)')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-16-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This dataset has the most interesting anomaly that we found. Consistent data collection does not begin until March, but once March hits, we have a massive anomaly. Starting on about March 2nd, we begin a period of high blocking, which does not fully end until about April 30th. The peak of the event runs from March 24th until April 18th. During that timeframe, we have an absurdly high average blocking percentage. Almost the entire entire increase in blocking percentage is TCP/IP blocking (the blocking using a TCP RST flag). Something is happening here. Once we found this anomaly, we decided that it would be the center of our analysis.</p>
<div id="4356fd35" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_mean(data):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (data.<span class="bu">sum</span>() <span class="op">-</span> data[<span class="st">"False"</span>]) <span class="op">/</span> data.<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="53c5d8a7" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>blocking_start <span class="op">=</span> <span class="st">"2022-03-24"</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>blocking_end <span class="op">=</span> <span class="st">"2022-04-18"</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>curr_data <span class="op">=</span> web_data[<span class="st">"hr"</span>][<span class="st">"2022"</span>]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>inner_range <span class="op">=</span> (curr_data.index <span class="op">&gt;=</span> start_date) <span class="op">&amp;</span> (curr_data.index <span class="op">&lt;=</span> end_date)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>outer_range <span class="op">=</span> (curr_data.index <span class="op">&lt;</span> start_date) <span class="op">|</span> (curr_data.index <span class="op">&gt;</span> end_date)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>during <span class="op">=</span> curr_data[inner_range].groupby(<span class="st">'blocking'</span>).size()</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>outside <span class="op">=</span> curr_data[outer_range].groupby(<span class="st">'blocking'</span>).size()</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Croatia 2022"</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Blocking Percentage During Anomaly: </span><span class="sc">{</span><span class="bu">round</span>(calculate_mean(during), <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Blocking Percentage Outside of Anomaly: </span><span class="sc">{</span><span class="bu">round</span>(calculate_mean(outside), <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Croatia 2022
Blocking Percentage During Anomaly: 0.1586
Blocking Percentage Outside of Anomaly: 0.0216</code></pre>
</div>
</div>
<p>As we can see, the percentage of blocked websites during the anomalies spike (March 24th - April 18th) jumps from 2.2% all the way to 15.9%. That kind of jump does not appear to be from random chance. We will discuss the statistical significance of this during the models section.</p>
<div id="6b17f786" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> calculate_mean(web_data[<span class="st">"np"</span>][<span class="st">"2022"</span>].groupby(<span class="st">'blocking'</span>).size())</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Blocking Percentage Nepal 2022: </span><span class="sc">{</span><span class="bu">round</span>(temp, <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> calculate_mean(web_data[<span class="st">"by"</span>][<span class="st">"2022"</span>].groupby(<span class="st">'blocking'</span>).size())</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Blocking Percentage Belarus 2022: </span><span class="sc">{</span><span class="bu">round</span>(temp, <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Blocking Percentage Nepal 2022: 0.0365
Blocking Percentage Belarus 2022: 0.0713</code></pre>
</div>
</div>
<p>These are the blocking percentages for Nepal and Belarus during that same year for reference.</p>
<p>Due to the drastic increase in blocking compared to not only its own year, but Belarus, we decided to investigate further. Belarus and Croatia are close enough to each other within the internet, which means that significant outside network factors are unlikely to be the source of the anomaly. The only other options would be</p>
<ol type="1">
<li>A censorship event</li>
<li>An internal network failure</li>
</ol>
<p>To see whether option 2 was likely or not, we decided to look at the difference in blocking percentage by domain. If the issue was an internal network failure, then all sites’ blocking percentage would go up by a similar amount. If the percentage is inconsistent, that would lead us to believe that it was the result of firewall reconfiguration (whether intentional or accidental). So we created the figures below to analyze these differences.</p>
<div id="d50421cc" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate fraction of events blocked per input</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_domain_graph(temp):</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    baseline <span class="op">=</span> temp.groupby(<span class="st">'input'</span>).size()</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    frac_dns_grouped <span class="op">=</span> (temp[temp[<span class="st">"blocking"</span>] <span class="op">==</span> <span class="st">"dns"</span>].groupby(<span class="st">'input'</span>).size() <span class="op">/</span> baseline).dropna().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    frac_httpdiff_grouped <span class="op">=</span> (temp[temp[<span class="st">"blocking"</span>] <span class="op">==</span> <span class="st">"http-diff"</span>].groupby(<span class="st">'input'</span>).size() <span class="op">/</span> baseline).dropna().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    frac_httpfail_grouped <span class="op">=</span> (temp[temp[<span class="st">"blocking"</span>] <span class="op">==</span> <span class="st">"http-failure"</span>].groupby(<span class="st">'input'</span>).size() <span class="op">/</span> baseline).dropna().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    frac_tcp_grouped <span class="op">=</span> (temp[temp[<span class="st">"blocking"</span>] <span class="op">==</span> <span class="st">"tcp_ip"</span>].groupby(<span class="st">'input'</span>).size() <span class="op">/</span> baseline).dropna().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    all_grouped <span class="op">=</span> pd.DataFrame({<span class="st">'dns'</span>: frac_dns_grouped, <span class="st">'httpdiff'</span>: frac_httpdiff_grouped, <span class="st">'httpfail'</span>: frac_httpfail_grouped, <span class="st">'tcp'</span>: frac_tcp_grouped}).fillna(<span class="dv">0</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    nn <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    top_n_idx <span class="op">=</span> all_grouped.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>).sort_values(ascending<span class="op">=</span><span class="va">False</span>)[<span class="dv">0</span>:nn].index</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    top_n <span class="op">=</span> all_grouped.loc[top_n_idx]</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    c_top_n <span class="op">=</span> top_n.cumsum(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">5</span>, <span class="dv">20</span>]</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    plt.barh(top_n.index[::<span class="op">-</span><span class="dv">1</span>].<span class="bu">str</span>.<span class="bu">slice</span>(<span class="dv">0</span>,<span class="dv">60</span>), top_n[<span class="st">'dns'</span>].iloc[::<span class="op">-</span><span class="dv">1</span>], label<span class="op">=</span><span class="st">'dns'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    plt.barh(top_n.index[::<span class="op">-</span><span class="dv">1</span>].<span class="bu">str</span>.<span class="bu">slice</span>(<span class="dv">0</span>,<span class="dv">60</span>), top_n[<span class="st">'httpdiff'</span>].iloc[::<span class="op">-</span><span class="dv">1</span>], left<span class="op">=</span>c_top_n.iloc[::<span class="op">-</span><span class="dv">1</span>,<span class="dv">0</span>], label<span class="op">=</span><span class="st">'httpdiff'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    plt.barh(top_n.index[::<span class="op">-</span><span class="dv">1</span>].<span class="bu">str</span>.<span class="bu">slice</span>(<span class="dv">0</span>,<span class="dv">60</span>), top_n[<span class="st">'httpfail'</span>].iloc[::<span class="op">-</span><span class="dv">1</span>], left<span class="op">=</span>c_top_n.iloc[::<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>], label<span class="op">=</span><span class="st">'httpfail'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    plt.barh(top_n.index[::<span class="op">-</span><span class="dv">1</span>].<span class="bu">str</span>.<span class="bu">slice</span>(<span class="dv">0</span>,<span class="dv">60</span>), top_n[<span class="st">'tcp'</span>].iloc[::<span class="op">-</span><span class="dv">1</span>], left<span class="op">=</span>c_top_n.iloc[::<span class="op">-</span><span class="dv">1</span>,<span class="dv">2</span>], label<span class="op">=</span><span class="st">'tcp'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    plt.margins(y<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    plt.grid()</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Top </span><span class="sc">{</span>nn<span class="sc">}</span><span class="ss"> Blocked Sites'</span>)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'Fraction of events'</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> all_grouped</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="4409a12f" class="cell" data-execution_count="46">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>outer_grouped <span class="op">=</span> make_domain_graph(web_data[<span class="st">"hr"</span>][<span class="st">"2022"</span>][outer_range])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows us the top 100 most frequently blocked domains outside of the anomaly time. We can see that the 100th most blocked domain is blocked well under 10% of the time. This is a low blocking percentage. This shows that Croatia has some consistently blocked pages, but relatively few.</p>
<p>Croatia’s normal web blocking appears to use a mixture of all 4 blocking types.</p>
<p>DNS blocking appears to be used for “objectionable” websites. In Croatia’s case, it is used for gambling sites (casino.com and williamhill.com), news services (sputniknews.com), a terrorist group’s homepage (kurtuluscephesi.com), a bookmarking service (delicious.com, possibly defunct) and a man in the middle service (mitm.watch). By far the most confusing blocked site is internetarchive.org. This site is used to cache deleted webpages. We are not certain why this would be blocked.</p>
<p>Httpdiff seems to be primarily used for LGBTQ+ content, which Croatia blocks due to laws against LGBTQ+ individuals in the country (gaytoday.com and lgbtglobalfaith.org). It is also used for a website that we could not find any information on (freerk.org).</p>
<p>Httpfail is also used for primarily gambling services, though it is unclear why some services use DNS level blocking, and others use Httpfail type blocking (royalvegas.com, sportingbet.com).</p>
<p>Finally, the most interesting is the TCP level blocking, as the anomaly is primarily TCP level blocking. It also appears to be primarily blocking proxy services (tor, proxyweb.net) and “objectionable” content, such as dating services (matrimony.org), and sexual health related information (iwhc.org and hivandhepatitis.com)</p>
<p>It appears that certain websites are consistently blocked. Many of the blocked sites are focused on controversial topics (like LGBTQ+ topics), firewal bypassing services (like proxies), Russian media, and adult content/vices (casinos, adult videos, etc…). These are things commonly blocked by many countries, and not usually considered censorship. Nothing in this list stands out significantly. What is interesting is to then compare this to the top 100 blocked sites during the anomaly.</p>
<div id="0c1e9c58" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>inner_grouped <span class="op">=</span> make_domain_graph(web_data[<span class="st">"hr"</span>][<span class="st">"2022"</span>][inner_range])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Obviously, a lot more of the internet is blocked here than it was before. In the outer range, the 100th most blocked site sits at around 5% blocking, which is most likely standard errors. Here, the 100th most blocked site is blocked over 40% of the time. That is a drastic difference. The majority of the increase is of course TCP level blocking. Despite this, it is hard to see what the most increased sites are. To more accurately analyze the difference, we’ve created a dataframe showing the sites with the highest difference in blocking percentage between inside and outside of the anomaly.</p>
<div id="19c47101" class="cell" data-execution_count="22">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get blocking events in small date range</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>summed <span class="op">=</span> (inner_grouped <span class="op">-</span> outer_grouped).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>summed.to_frame(<span class="st">"Summed"</span>).sort_values(by<span class="op">=</span><span class="st">"Summed"</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Summed</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">input</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">i2p2.de</td>
<td>0.835766</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ohmynews.com</td>
<td>0.683486</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">prolife.com</td>
<td>0.678571</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ifeminists.com</td>
<td>0.671265</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">lgbt.foundation</td>
<td>0.654279</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">vanguardnewsnetwork.com</td>
<td>0.603896</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">privacytools.io</td>
<td>0.595041</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">youporn.com</td>
<td>0.562254</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">rxmarijuana.com</td>
<td>0.515406</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">thegooddrugsguide.com</td>
<td>0.506266</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">topdrawers.com</td>
<td>0.497024</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">datpiff.com</td>
<td>0.493789</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">hackforums.net</td>
<td>0.491833</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">winespectator.com</td>
<td>0.490991</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">xvideos.com</td>
<td>0.490741</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">tobacco.org</td>
<td>0.484733</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">venus.com</td>
<td>0.482143</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">sportsinteraction.com</td>
<td>0.472936</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">jmarshall.com</td>
<td>0.469161</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">monacogoldcasino.com</td>
<td>0.467857</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">msftncsi.com/ncsi.txt</td>
<td>0.464675</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">msftconnecttest.com/connecttest.txt</td>
<td>0.464425</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">creativecommons.org</td>
<td>0.459805</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">pokerpages.com</td>
<td>0.459797</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">avaaz.org</td>
<td>0.459399</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">idsoftware.com</td>
<td>0.455827</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ned.org</td>
<td>0.454787</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hacktivismo.com</td>
<td>0.453684</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">zeit.de</td>
<td>0.450285</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ilo.org</td>
<td>0.448381</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>These represent the 30 sites with the biggest difference in blocking percentage inside and outside of our anomaly. They fit into a couple categories.</p>
<ul>
<li>Proxies/Hacking/P2P Clients - These are a similar group of sites. All of these sites are ways for users to access content through non-standard channels. This is the most significant group. The single biggest increase is a P2P client (i2p2.de). Multiple of the largest increases belong to this group (i2p2.de, privacytools.io, hackforums.net, etc…)</li>
<li>Abortion Discussion - Abortion is a heavily regulated procedure in Croatia, and thus it is logical that abortion discussion is heavily moderated. The banned sites are a mixture of pro-choice (ifeminist.org), and pro-life (prolife.com).</li>
<li>News Sources - Multiple news sources are censored heavily during the anomaly. Most notably, we have a South Korean news source (ohmynews.com), and a major white supremacist news source (vanguardnewsnetwork.com). While the white supremacist news ban makes sense, there seems to be no major reason to ban the South Korean news source.</li>
<li>Adult Entertainment - Many countries restrict adult media, and this is no exception. Adult video sites (xvideos.com, youporn.com, venus.com), and adult toy sites (topdrawer.com) are all blocked during this time period.</li>
<li>Gambling - Many gambling sites are restricted during the anomaly (datpiff.com, sportsinteraction.com, monacogoldcasino.com). Gambling was legalized a decade ago in Croatia, and is still controversial, making these bans unsurprising.</li>
<li>Controlled Substance Sites - Many sites relating to controlled substances are inaccessible during this time (rxmarijuana.com, thegooddrugsguide.com, winespectator.com, tobacco.org)</li>
<li>LGBTQ+ Organizations - Croatia does not allow gay marriage to this day, making bans on LGBTQ+ advocacy groups interesting, and worth investigation (lgbt.foundation)</li>
</ul>
<p>Overall, the array of banned sites is wide, but all are sites that are commonly banned in countries with censorship in place. It is good for us to analyze which sites are banned, but we did not find anything surprising here.</p>
<p>Due to this intriguing find with Croatia 2022, we decided to download Croatia 2021 and 2023 to compare against, and we will discuss them below.</p>
</section>
<section id="croatia-2021" class="level5">
<h5 class="anchored" data-anchor-id="croatia-2021">Croatia 2021</h5>
<div id="2a632b6e" class="cell" data-execution_count="47">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>make_basic_visualization(<span class="st">"hr"</span>, <span class="st">"2021"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-24-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-24-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With the 2021 data, we see many of the same issues that plagued the Nepal dataset. There are some obvious gaps, where no tests were run for several weeks at a time. This dataset has less gaps than nepal, but has enough to make the data less useful than it would otherwise be. We do however see some pretty significant spikes in httpfailure type blocking events. These spikes never last long, but do spike up beyond 35%, which is significant. If this dataset was more complete, it would be worthwhile to analyze. However, due to the sparse data collection, we will not analyze this dataset further.</p>
</section>
<section id="croatia-2023" class="level5">
<h5 class="anchored" data-anchor-id="croatia-2023">Croatia 2023</h5>
<div id="44cca6c7" class="cell" data-execution_count="24">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>make_basic_visualization(<span class="st">"hr"</span>, <span class="st">"2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-25-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="1dea0658" class="cell" data-execution_count="25">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>temp <span class="op">=</span> calculate_mean(web_data[<span class="st">"hr"</span>][<span class="st">"2023"</span>].groupby(<span class="st">'blocking'</span>).size())</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Blocking Percentage Croatia 2022: </span><span class="sc">{</span><span class="bu">round</span>(temp, <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Blocking Percentage Croatia 2022: 0.0194</code></pre>
</div>
</div>
<p>This year of data is exactly what we expect to see out of a non-censored country. At worst, we see a 3% blocking percentage, and our average is under 2%. This is similar to our 2022 mean outside of the anomaly (1.94% vs 2.16%). This helps us see what the Croatian dataset should look like. There is no anomaly occurring during Spring of this year, which helps us show that the anomaly is truly unexpected. Something happened during that time that seemingly has not happened before or since. We want to figure out what it is. In the next section, we will go over some models we intend to use to analyze our model.</p>
</section>
</section>
<section id="models" class="level2">
<h2 class="anchored" data-anchor-id="models">Models</h2>
<section id="basic-anomaly-detection" class="level5">
<h5 class="anchored" data-anchor-id="basic-anomaly-detection">Basic Anomaly Detection</h5>
<p>First we try to find potential anomalies automatically using the <span class="math inline">\(95\%\)</span> quantile as a threshold for the mean blocking events. This produces the following plot of potentially interesting regions of time to investigate further.</p>
<div id="c344f429" class="cell" data-execution_count="26">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the data of interest</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>country <span class="op">=</span> <span class="st">'hr'</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>year <span class="op">=</span> <span class="st">'2022'</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> web_data[country][year]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> fracs[country][year].drop(<span class="st">'False'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Get means and standard deviations</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> pd.DataFrame(means[country][year])</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> m.reindex(<span class="bu">sorted</span>(m.columns), axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> m.drop(<span class="st">'False'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> pd.DataFrame(stds[country][year])</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> s.reindex(<span class="bu">sorted</span>(s.columns), axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> s.drop(<span class="st">'False'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="3b5ac1fc" class="cell" data-execution_count="27">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform IQR checks on the mean</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> m.quantile([<span class="fl">0.05</span>, <span class="fl">0.95</span>])</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>lb <span class="op">=</span> iqr.iloc[<span class="dv">0</span>]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>ub <span class="op">=</span> iqr.iloc[<span class="dv">1</span>]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for anomalies outside of ranges</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>au <span class="op">=</span> (m <span class="op">&gt;</span> ub)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>al <span class="op">=</span> (m <span class="op">&lt;</span> lb)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot anomalies</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">4</span><span class="op">*</span><span class="bu">len</span>(m.columns)))</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, c <span class="kw">in</span> <span class="bu">enumerate</span>(m.columns):</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get color values</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#color = au[c].apply(lambda x: palette[len(m.columns)+1] if x is True else palette[i])</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    anom <span class="op">=</span> m[au]</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plot</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="bu">len</span>(m.columns), <span class="dv">1</span>, i<span class="op">+</span><span class="dv">1</span>)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    plt.plot(m[c], label<span class="op">=</span>c, color<span class="op">=</span>palette[i])</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    plt.scatter(anom.index, anom[c], s<span class="op">=</span><span class="dv">100</span>, color<span class="op">=</span>palette[<span class="bu">len</span>(m.columns)<span class="op">+</span><span class="dv">1</span>], marker<span class="op">=</span><span class="st">'*'</span>)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Potential Anomalies in </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss"> Blocking Type'</span>)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these plots, we chose 3 date ranges of interest:</p>
<ul>
<li><ol type="a">
<li>March 1st 2022 to April 30th 2022</li>
</ol></li>
<li><ol start="2" type="a">
<li>June 15th 2022 to September 1st 2022</li>
</ol></li>
<li><ol start="3" type="a">
<li>December 5th 2022 to December 31st 2022</li>
</ol></li>
</ul>
</section>
<section id="statistical-tests" class="level5">
<h5 class="anchored" data-anchor-id="statistical-tests">Statistical Tests</h5>
<p>Next we’d like to characterize the dataset and understand more what is happening inside of these regions of interest versus outside of the regions. To do this we have to first check some basic statistical tests.</p>
</section>
<section id="z-tests" class="level5">
<h5 class="anchored" data-anchor-id="z-tests">Z-Tests</h5>
<div id="82be0508" class="cell" data-execution_count="28">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define ranges</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>start_dateA <span class="op">=</span> <span class="st">'2022-03-01'</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>end_dateA <span class="op">=</span> <span class="st">'2022-04-30'</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>start_dateB <span class="op">=</span> <span class="st">'2022-06-15'</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>end_dateB <span class="op">=</span> <span class="st">'2022-09-01'</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>start_dateC <span class="op">=</span> <span class="st">'2022-12-05'</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>end_dateC <span class="op">=</span> <span class="st">'2022-12-31'</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Get indices</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>w_inner_idxA <span class="op">=</span> (w.index <span class="op">&gt;=</span> start_dateA) <span class="op">&amp;</span> (w.index <span class="op">&lt;=</span> end_dateA)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>m_inner_idxA <span class="op">=</span> (m.index <span class="op">&gt;=</span> start_dateA) <span class="op">&amp;</span> (m.index <span class="op">&lt;=</span> end_dateA)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>w_outer_idxA <span class="op">=</span> <span class="op">~</span>w_inner_idxA</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>m_outer_idxA <span class="op">=</span> <span class="op">~</span>m_inner_idxA</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>w_inner_idxB <span class="op">=</span> (w.index <span class="op">&gt;=</span> start_dateB) <span class="op">&amp;</span> (w.index <span class="op">&lt;=</span> end_dateB)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>m_inner_idxB <span class="op">=</span> (m.index <span class="op">&gt;=</span> start_dateB) <span class="op">&amp;</span> (m.index <span class="op">&lt;=</span> end_dateB)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>w_outer_idxB <span class="op">=</span> <span class="op">~</span>w_inner_idxB</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>m_outer_idxB <span class="op">=</span> <span class="op">~</span>m_inner_idxB</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>w_inner_idxC <span class="op">=</span> (w.index <span class="op">&gt;=</span> start_dateC) <span class="op">&amp;</span> (w.index <span class="op">&lt;=</span> end_dateC)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>m_inner_idxC <span class="op">=</span> (m.index <span class="op">&gt;=</span> start_dateC) <span class="op">&amp;</span> (m.index <span class="op">&lt;=</span> end_dateC)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>w_outer_idxC <span class="op">=</span> <span class="op">~</span>w_inner_idxC</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>m_outer_idxC <span class="op">=</span> <span class="op">~</span>m_inner_idxC</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data into ranges</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>w_innerA <span class="op">=</span> w[w_inner_idxA]</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>m_innerA <span class="op">=</span> m[m_inner_idxA]</span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>w_outerA <span class="op">=</span> w[w_outer_idxA]</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>m_outerA <span class="op">=</span> m[m_outer_idxA]</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>w_innerB <span class="op">=</span> w[w_inner_idxB]</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>m_innerB <span class="op">=</span> m[m_inner_idxB]</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>w_outerB <span class="op">=</span> w[w_outer_idxB]</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>m_outerB <span class="op">=</span> m[m_outer_idxB]</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>w_innerC <span class="op">=</span> w[w_inner_idxC]</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>m_innerC <span class="op">=</span> m[m_inner_idxC]</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>w_outerC <span class="op">=</span> w[w_outer_idxC]</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>m_outerC <span class="op">=</span> m[m_outer_idxC]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>First we perform a two sample Z-Test in order to determine if the mean values of each type of blocking method are different within each date range versus outside of each date range.</p>
<p>We run the Z-Test for date range <strong>(a)</strong> versus outside of the date range:</p>
<div id="a5d82d1d" class="cell" data-execution_count="29">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the 2 Sample Z-Test</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(ztest(m_innerA, m_outerA, value<span class="op">=</span><span class="dv">0</span>), index<span class="op">=</span>[<span class="st">'Z Statistic'</span>, <span class="st">'p-value'</span>], columns<span class="op">=</span>m_innerA.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dns</th>
<th data-quarto-table-cell-role="th">http-diff</th>
<th data-quarto-table-cell-role="th">http-failure</th>
<th data-quarto-table-cell-role="th">tcp_ip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Z Statistic</td>
<td>6.041636e+00</td>
<td>1.880703e+01</td>
<td>4.169273</td>
<td>1.378721e+01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">p-value</td>
<td>1.525592e-09</td>
<td>6.613715e-79</td>
<td>0.000031</td>
<td>3.043069e-43</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Given that all of the blocking event types pass the p-value threshold of <span class="math inline">\(0.05\)</span>, we can reject the null hypothesis that the distributions of these blocking events have the same means. This likely means that the <strong>(a)</strong> date range distribution of blocking events are all distinct from other times throughout the year.</p>
<p>Next we run the Z-Test for the date range <strong>(b)</strong> versus outside of the date range:</p>
<div id="9d2a514c" class="cell" data-execution_count="30">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the 2 Sample Z-Test</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(ztest(m_innerB, m_outerB, value<span class="op">=</span><span class="dv">0</span>), index<span class="op">=</span>[<span class="st">'Z Statistic'</span>, <span class="st">'p-value'</span>], columns<span class="op">=</span>m_innerB.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dns</th>
<th data-quarto-table-cell-role="th">http-diff</th>
<th data-quarto-table-cell-role="th">http-failure</th>
<th data-quarto-table-cell-role="th">tcp_ip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Z Statistic</td>
<td>-0.453515</td>
<td>-1.926296</td>
<td>1.222851e+01</td>
<td>-2.230284</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">p-value</td>
<td>0.650178</td>
<td>0.054067</td>
<td>2.189270e-34</td>
<td>0.025729</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Given that only the <code>http-failure</code> and <code>tcp_ip</code> blocking events pass the p-value threshold of <span class="math inline">\(0.05\)</span>, we can only reject the null hypothesis that the distributions have the same means inside versus outside of the date range.</p>
<p>Finally we run the Z-Test for the date range <strong>(c)</strong> versus outside of the date range:</p>
<div id="0b9b75e1" class="cell" data-execution_count="31">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the 2 Sample Z-Test</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(ztest(m_innerC, m_outerC, value<span class="op">=</span><span class="dv">0</span>), index<span class="op">=</span>[<span class="st">'Z Statistic'</span>, <span class="st">'p-value'</span>], columns<span class="op">=</span>m_innerC.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dns</th>
<th data-quarto-table-cell-role="th">http-diff</th>
<th data-quarto-table-cell-role="th">http-failure</th>
<th data-quarto-table-cell-role="th">tcp_ip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Z Statistic</td>
<td>6.296285e+00</td>
<td>-2.966596</td>
<td>-1.077220</td>
<td>-1.640400</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">p-value</td>
<td>3.048631e-10</td>
<td>0.003011</td>
<td>0.281382</td>
<td>0.100922</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We can only reject the null hypothesis for the <code>http-diff</code> and <code>dns</code> blocking event types in this case, which matches our assumptions from the detected anomalies from above.</p>
</section>
<section id="time-series-characterization" class="level5">
<h5 class="anchored" data-anchor-id="time-series-characterization">Time Series Characterization</h5>
<p>Next we try to validate some properties about the time series itself, namely:</p>
<ul>
<li>Stationarity - Whether the data is not a function of time</li>
<li>Autocorrelation - Whether the time series dataset has any lags which are related to the current time step</li>
<li>Partial Autocorrelation - Whether the time series is related to its past values while controlling for intervening values which can indicate the influence of lagged observations on the current observation excluding other lags</li>
</ul>
<p>To determine stationarity, we use the Augmented Dickey-Fuller test, which is a statistical test that tries to evaluate whether the null hypothesis that a particular time series dataset is non-stationary, meaning that the data is a function of time. If the test’s p-value is below a significance threshold, we can reject this and assume our data is stationary, which makes modeling the relationship a bit less complicated.</p>
<div id="43e6fab6" class="cell" data-execution_count="32">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute rolling totals, means, and standard deviations</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>k<span class="op">=</span><span class="dv">1</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>totals1 <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>means1 <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>stds1 <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>quarts1 <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>quants1 <span class="op">=</span> {country : { year : {} <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country] } <span class="cf">for</span> country <span class="kw">in</span> blocking_events}</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> country <span class="kw">in</span> blocking_events:</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> year <span class="kw">in</span> blocking_events[country]:</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> event_type <span class="kw">in</span> blocking_events[country][year]:</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Calculate date range</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>            date_range <span class="op">=</span> pd.date_range(start<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">-01-01'</span>, end<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">-12-31'</span>, freq<span class="op">=</span><span class="st">'D'</span>)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Fill all empty events with zeroes</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>            d <span class="op">=</span> blocking_events[country][year][event_type]</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>            tmp <span class="op">=</span> d.groupby(d.index).size()</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>            totals1[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).<span class="bu">sum</span>().dropna()</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>            means1[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().dropna()</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>            stds1[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).std().dropna()</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>            quarts1[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().quantile([<span class="fl">0.25</span>, <span class="fl">0.75</span>]).dropna()</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>            quants1[country][year][event_type] <span class="op">=</span> tmp.copy().reindex(date_range, fill_value<span class="op">=</span><span class="dv">0</span>).rolling(window<span class="op">=</span>k).mean().quantile([<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">0.9</span>, <span class="fl">0.99</span>]).dropna()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="a1578688" class="cell" data-execution_count="33">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute ADF</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> totals1[<span class="st">'hr'</span>][<span class="st">'2022'</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>tdf <span class="op">=</span> pd.DataFrame(t).drop(<span class="st">'False'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>adf_tests <span class="op">=</span> { typ : [adfuller(t[typ])[<span class="dv">0</span>], adfuller(t[typ])[<span class="dv">1</span>]] <span class="cf">for</span> typ <span class="kw">in</span> blocking_events[<span class="st">'hr'</span>][<span class="st">'2022'</span>] <span class="cf">if</span> typ <span class="kw">not</span> <span class="kw">in</span> [<span class="st">'False'</span>]}</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(adf_tests, index<span class="op">=</span>[<span class="st">'ADF Statistic'</span>, <span class="st">'p-value'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dns</th>
<th data-quarto-table-cell-role="th">http-diff</th>
<th data-quarto-table-cell-role="th">http-failure</th>
<th data-quarto-table-cell-role="th">tcp_ip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">ADF Statistic</td>
<td>-5.462238</td>
<td>-2.93027</td>
<td>-4.336395</td>
<td>-2.706767</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">p-value</td>
<td>0.000003</td>
<td>0.04194</td>
<td>0.000384</td>
<td>0.072875</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Since the p-values of all of the blocking events except for <code>tcp_ip</code> is below the threshold <span class="math inline">\(0.05\)</span>, then we can safely reject the null hypothesis that the time series data is non-stationary in those specific cases. This means that the data in the other blocking event types is likely to be stationary in the 0th order. For <code>tcp_ip</code> more analysis is necessary to determine its characteristics.</p>
<p>In order to determine what point that the <code>tcp_ip</code> blocking events become stationary, we use the 1st order and 2nd order differential tests and the autorrelation of those.</p>
<div id="fab11fdc" class="cell" data-execution_count="34">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">15</span>, <span class="dv">10</span>]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> palette[<span class="bu">len</span>(tdf.columns)<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate differentials</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>diff_0 <span class="op">=</span> tdf[<span class="st">'tcp_ip'</span>]</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>diff_1 <span class="op">=</span> diff_0.diff().dropna()</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>diff_2 <span class="op">=</span> diff_1.diff().dropna()</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot all differentials and their autocorrelation</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>,<span class="dv">2</span>, sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].plot(diff_0, color<span class="op">=</span>color)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'Original tcp_ip Series'</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>plot_acf(diff_0, ax<span class="op">=</span>axes[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_ylim(<span class="op">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 1st order differencing</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].plot(diff_1, color<span class="op">=</span>color)</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'1st order diff'</span>)</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_ymargin(<span class="fl">0.1</span>)</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>plot_acf(diff_1, ax<span class="op">=</span>axes[<span class="dv">1</span>, <span class="dv">1</span>])</span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_ylim(<span class="op">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>)</span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 2nd order differencing</span></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">0</span>].plot(diff_2, color<span class="op">=</span>color)</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>, <span class="dv">0</span>].set_title(<span class="st">'2nd order diff'</span>)</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>plot_acf(diff_2, ax<span class="op">=</span>axes[<span class="dv">2</span>, <span class="dv">1</span>])</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>,<span class="dv">1</span>].set_ylim(<span class="op">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>)</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>,<span class="dv">3</span>):</span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> line <span class="kw">in</span> axes[i,<span class="dv">1</span>].get_lines():</span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>        line.set_color(color)</span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> marker <span class="kw">in</span> axes[i,<span class="dv">1</span>].collections:</span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a>        marker.set_color(color)</span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-35-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these graphs we can conclude that the data becomes stationary likely at its 1st order differential given that the peaks in the autocorrelation factor plot settle close to the threshold very quickly.</p>
<p>Next we run autocorrelation and partial autocorrelation factor analysis on the rest of the raw totals to see what types of intra-series relationships there are.</p>
<div id="3ddc6d6c" class="cell" data-execution_count="35">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="bu">len</span>(tdf.columns)<span class="op">*</span><span class="dv">6</span>, <span class="dv">15</span>]</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="bu">len</span>(tdf.columns), <span class="dv">3</span>, sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, t <span class="kw">in</span> <span class="bu">enumerate</span>(tdf.columns):</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    axes[i,<span class="dv">0</span>].plot(tdf[t], color<span class="op">=</span>palette[i])</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    axes[i,<span class="dv">0</span>].set_title(<span class="ss">f'Total </span><span class="sc">{</span>t<span class="sc">}</span><span class="ss"> Events'</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    plot_pacf(tdf[t].dropna(), ax<span class="op">=</span>axes[i,<span class="dv">1</span>], color<span class="op">=</span>palette[i])</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    axes[i,<span class="dv">1</span>].<span class="bu">set</span>(ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">1.1</span>,<span class="fl">1.1</span>))</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    plot_acf(tdf[t].dropna(), ax<span class="op">=</span>axes[i,<span class="dv">2</span>], color<span class="op">=</span>palette[i])</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    axes[i,<span class="dv">2</span>].<span class="bu">set</span>(ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">1.1</span>, <span class="fl">1.1</span>))</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>,<span class="dv">3</span>):</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> line <span class="kw">in</span> axes[i,j].get_lines():</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>            line.set_color(palette[i])</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> marker <span class="kw">in</span> axes[i,j].collections:</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>            marker.set_color(palette[i])</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-36-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these plots we can see that most of the models have 1st, 2nd, and 3rd order partial autocorrelation factors above the threshold of acceptance, likely meaning that there is some intra-day relationships from past days up to those size windows. None of the blocking events seem to indicate that they have any seasonality due to the fact that there is steady dropoff without any regular peaks. It is also interesting to see that <code>tcp-ip</code> has peaks at orders 1, 3, 5, 9, and 10 which are potential parameters to try during modeling.</p>
<p>In terms of the Z-Test that was done earlier, there are limits on what conclusions can be drawn due to the fact that all of the blocking events are not exactly independently distributed, however due to the fact that the autocorrelation drops of farily steadily in all cases, it can be concluded that statistically it is likely for the different date ranges to actually have the differences from the means that we observed.</p>
<p>As for autocorrelation, most of the different events have steady decline in autocorrelation, meaning that the series may have fairly short term memory of its events. There do not seem to be any strong trends or seasonal patterns which seems consistent with just visual inspection of the data as well.</p>
</section>
<section id="time-series-modeling" class="level5">
<h5 class="anchored" data-anchor-id="time-series-modeling">Time Series Modeling</h5>
<p>Now that we have characterized the data iself, we would like to build models of the data using the Auto Regressive Integrated Moving Average method (ARIMA). This method is split into 3 different parts:</p>
<ul>
<li><code>p</code> - The autoregressive (AR) term refers to the order in which the model depends on a specific lag factor</li>
<li><code>d</code> - The integration (I) term refers to which order that the data is stationary in</li>
<li><code>q</code> - The moving average (MA) term refers to where the output depends only on lagged errors</li>
</ul>
<p>For every blocking event except <code>tcp_ip</code> we are assuming the data to be stationary which means its <code>d</code> term is nonzero (and from our previous explorations we’ve determined it is likely <span class="math inline">\(d=1\)</span>).</p>
<p>We test a few different models for each method and compare their AIC and BIC values.</p>
<div id="56bd3bcb" class="cell" data-execution_count="36">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try out different ARMA terms</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ar_orders <span class="op">=</span> [<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>ma_orders <span class="op">=</span> [<span class="dv">0</span>,<span class="dv">1</span>]</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Type and color</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>typ <span class="op">=</span> tdf.columns[i]</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> palette[i]</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>outcol <span class="op">=</span> palette[<span class="bu">len</span>(tdf.columns)<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> tdf[typ]</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">8</span><span class="op">*</span><span class="bu">len</span>(ar_orders), <span class="dv">4</span><span class="op">*</span><span class="bu">len</span>(ma_orders)]</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all models</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>fitted_models <span class="op">=</span> {}</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.figure(figsize=(12*len(ma_orders), 4*len(ar_orders)))</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="bu">len</span>(ma_orders), <span class="bu">len</span>(ar_orders), sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c, ar <span class="kw">in</span> <span class="bu">enumerate</span>(ar_orders):</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>    fitted_models[ar] <span class="op">=</span> {}</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r, ma <span class="kw">in</span> <span class="bu">enumerate</span>(ma_orders):</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>        ar_model <span class="op">=</span> ARIMA(d, order<span class="op">=</span>(ar, <span class="dv">0</span>, ma))</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>        ar_model_fit <span class="op">=</span> ar_model.fit()</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>        fitted_models[ar][ma] <span class="op">=</span> ar_model_fit</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(d, color<span class="op">=</span>color)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(ar_model_fit.fittedvalues, color<span class="op">=</span>outcol, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>        axes[r,c].set_title(<span class="ss">f'</span><span class="sc">{</span>typ<span class="sc">}</span><span class="ss"> ARMA Model p=</span><span class="sc">{</span>ar<span class="sc">}</span><span class="ss">, q=</span><span class="sc">{</span>ma<span class="sc">}</span><span class="ss">'</span>) <span class="co">#, AIC={ar_model_fit.aic}, BIC={ar_model_fit.bic}')</span></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>        axes[r,c].text(<span class="fl">0.02</span>,<span class="fl">0.98</span>, <span class="ss">f'AIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>aic<span class="sc">}</span><span class="ss">, BIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>bic<span class="sc">}</span><span class="ss">'</span>, ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'top'</span>, transform<span class="op">=</span>axes[r,c].transAxes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From this exploration of model parameters, we can see that the model with the lowest AIC as well as BIC is the model with <span class="math inline">\(p=1\)</span>, <span class="math inline">\(q=1\)</span>. This likely means that first order auto regression and first order moving average are decent predictors of future behavior in the <code>dns</code> data (therefore a period of 1 day likely predicts the next day).</p>
<div id="cdbfc8c6" class="cell" data-execution_count="37">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fitted_models[<span class="dv">1</span>][<span class="dv">1</span>].summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="37">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>SARIMAX Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>dns</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>365</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>ARIMA(1, 0, 1)</td>
<td data-quarto-table-cell-role="th">Log Likelihood</td>
<td>-1342.575</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 17 Mar 2025</td>
<td data-quarto-table-cell-role="th">AIC</td>
<td>2693.150</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:48:10</td>
<td data-quarto-table-cell-role="th">BIC</td>
<td>2708.750</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sample:</td>
<td>01-01-2022</td>
<td data-quarto-table-cell-role="th">HQIC</td>
<td>2699.350</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td>- 12-31-2022</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>opg</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>6.4474</td>
<td>2.522</td>
<td>2.556</td>
<td>0.011</td>
<td>1.503</td>
<td>11.391</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L1</td>
<td>0.8584</td>
<td>0.031</td>
<td>27.325</td>
<td>0.000</td>
<td>0.797</td>
<td>0.920</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ma.L1</td>
<td>-0.5676</td>
<td>0.048</td>
<td>-11.766</td>
<td>0.000</td>
<td>-0.662</td>
<td>-0.473</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sigma2</td>
<td>91.6184</td>
<td>2.054</td>
<td>44.615</td>
<td>0.000</td>
<td>87.594</td>
<td>95.643</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Ljung-Box (L1) (Q):</td>
<td>0.28</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>23501.89</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Q):</td>
<td>0.60</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Heteroskedasticity (H):</td>
<td>4.08</td>
<td data-quarto-table-cell-role="th">Skew:</td>
<td>4.28</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(H) (two-sided):</td>
<td>0.00</td>
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>41.37</td>
</tr>
</tbody>
</table>
<br><br>Warnings:<br>[1] Covariance matrix calculated using the outer product of gradients (complex-step).
</div>
</div>
<p>For the <code>http-diff</code> blocking events, we see that there are peaks in the partial autocorrelation function plots at 1,3,5, and 6, so we test these values for the AR orders.</p>
<div id="57859d2c" class="cell" data-execution_count="38">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try out different ARMA terms</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>ar_orders <span class="op">=</span> [<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>]</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>ma_orders <span class="op">=</span> [<span class="dv">0</span>,<span class="dv">1</span>]</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Type and color</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>typ <span class="op">=</span> tdf.columns[i]</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> palette[i]</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>outcol <span class="op">=</span> palette[<span class="bu">len</span>(tdf.columns)<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> tdf[typ]</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">8</span><span class="op">*</span><span class="bu">len</span>(ar_orders), <span class="dv">4</span><span class="op">*</span><span class="bu">len</span>(ma_orders)]</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all models</span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a>fitted_models <span class="op">=</span> {}</span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.figure(figsize=(12*len(ma_orders), 4*len(ar_orders)))</span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="bu">len</span>(ma_orders), <span class="bu">len</span>(ar_orders), sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb42-21"><a href="#cb42-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c, ar <span class="kw">in</span> <span class="bu">enumerate</span>(ar_orders):</span>
<span id="cb42-22"><a href="#cb42-22" aria-hidden="true" tabindex="-1"></a>    fitted_models[ar] <span class="op">=</span> {}</span>
<span id="cb42-23"><a href="#cb42-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r, ma <span class="kw">in</span> <span class="bu">enumerate</span>(ma_orders):</span>
<span id="cb42-24"><a href="#cb42-24" aria-hidden="true" tabindex="-1"></a>        ar_model <span class="op">=</span> ARIMA(d, order<span class="op">=</span>(ar, <span class="dv">0</span>, ma))</span>
<span id="cb42-25"><a href="#cb42-25" aria-hidden="true" tabindex="-1"></a>        ar_model_fit <span class="op">=</span> ar_model.fit()</span>
<span id="cb42-26"><a href="#cb42-26" aria-hidden="true" tabindex="-1"></a>        fitted_models[ar][ma] <span class="op">=</span> ar_model_fit</span>
<span id="cb42-27"><a href="#cb42-27" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(d, color<span class="op">=</span>color)</span>
<span id="cb42-28"><a href="#cb42-28" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(ar_model_fit.fittedvalues, color<span class="op">=</span>outcol, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb42-29"><a href="#cb42-29" aria-hidden="true" tabindex="-1"></a>        axes[r,c].set_title(<span class="ss">f'</span><span class="sc">{</span>typ<span class="sc">}</span><span class="ss"> ARMA Model p=</span><span class="sc">{</span>ar<span class="sc">}</span><span class="ss">, q=</span><span class="sc">{</span>ma<span class="sc">}</span><span class="ss">'</span>) <span class="co">#, AIC={ar_model_fit.aic}, BIC={ar_model_fit.bic}')</span></span>
<span id="cb42-30"><a href="#cb42-30" aria-hidden="true" tabindex="-1"></a>        axes[r,c].text(<span class="fl">0.02</span>,<span class="fl">0.98</span>, <span class="ss">f'AIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>aic<span class="sc">}</span><span class="ss">, BIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>bic<span class="sc">}</span><span class="ss">'</span>, ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'top'</span>, transform<span class="op">=</span>axes[r,c].transAxes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these plots we see that the model with the lowest AIC is where <span class="math inline">\(p=6\)</span> and <span class="math inline">\(q=1\)</span>, however the model with the lowest BIC is where <span class="math inline">\(p=3\)</span> and <span class="math inline">\(q=1\)</span>. Depending on whether we want to prioritize accuracy at the expense of using more data points for fitting, we would either choose the 6th or the 3rd order models for this blocking type. We can conclude however that a moving average term does make a slight difference on model accuracy, and that there are potentially 3rd order to 6th order terms that have a decent impact on model prediction.</p>
<div id="8e9ce439" class="cell" data-execution_count="39">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fitted_models[<span class="dv">6</span>][<span class="dv">1</span>].summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="39">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>SARIMAX Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>http-diff</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>365</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>ARIMA(6, 0, 1)</td>
<td data-quarto-table-cell-role="th">Log Likelihood</td>
<td>-1038.271</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 17 Mar 2025</td>
<td data-quarto-table-cell-role="th">AIC</td>
<td>2094.542</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:48:12</td>
<td data-quarto-table-cell-role="th">BIC</td>
<td>2129.641</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sample:</td>
<td>01-01-2022</td>
<td data-quarto-table-cell-role="th">HQIC</td>
<td>2108.491</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td>- 12-31-2022</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>opg</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>3.2879</td>
<td>1.981</td>
<td>1.659</td>
<td>0.097</td>
<td>-0.596</td>
<td>7.171</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L1</td>
<td>-0.0463</td>
<td>0.176</td>
<td>-0.263</td>
<td>0.793</td>
<td>-0.392</td>
<td>0.299</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L2</td>
<td>0.1937</td>
<td>0.086</td>
<td>2.245</td>
<td>0.025</td>
<td>0.025</td>
<td>0.363</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L3</td>
<td>0.1567</td>
<td>0.047</td>
<td>3.313</td>
<td>0.001</td>
<td>0.064</td>
<td>0.249</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L4</td>
<td>0.0414</td>
<td>0.045</td>
<td>0.929</td>
<td>0.353</td>
<td>-0.046</td>
<td>0.129</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L5</td>
<td>0.1431</td>
<td>0.039</td>
<td>3.689</td>
<td>0.000</td>
<td>0.067</td>
<td>0.219</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L6</td>
<td>0.2551</td>
<td>0.052</td>
<td>4.928</td>
<td>0.000</td>
<td>0.154</td>
<td>0.357</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ma.L1</td>
<td>0.4498</td>
<td>0.188</td>
<td>2.397</td>
<td>0.017</td>
<td>0.082</td>
<td>0.818</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">sigma2</td>
<td>17.2590</td>
<td>0.605</td>
<td>28.518</td>
<td>0.000</td>
<td>16.073</td>
<td>18.445</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Ljung-Box (L1) (Q):</td>
<td>0.01</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>5145.02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Q):</td>
<td>0.92</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Heteroskedasticity (H):</td>
<td>0.14</td>
<td data-quarto-table-cell-role="th">Skew:</td>
<td>2.84</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(H) (two-sided):</td>
<td>0.00</td>
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>20.49</td>
</tr>
</tbody>
</table>
<br><br>Warnings:<br>[1] Covariance matrix calculated using the outer product of gradients (complex-step).
</div>
</div>
<p>In the case of the <code>http-fail</code>, there are peaks at periods of 1, 2, and 3 in the partial autocorrelation factor plots, so we test out these in the AR terms.</p>
<div id="6f23b484" class="cell" data-execution_count="40">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try out different ARMA terms</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>ar_orders <span class="op">=</span> [<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>ma_orders <span class="op">=</span> [<span class="dv">0</span>,<span class="dv">1</span>]</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Type and color</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>typ <span class="op">=</span> tdf.columns[i]</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> palette[i]</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>outcol <span class="op">=</span> palette[<span class="bu">len</span>(tdf.columns)<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> tdf[typ]</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">8</span><span class="op">*</span><span class="bu">len</span>(ar_orders), <span class="dv">4</span><span class="op">*</span><span class="bu">len</span>(ma_orders)]</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all models</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>fitted_models <span class="op">=</span> {}</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.figure(figsize=(12*len(ma_orders), 4*len(ar_orders)))</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="bu">len</span>(ma_orders), <span class="bu">len</span>(ar_orders), sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c, ar <span class="kw">in</span> <span class="bu">enumerate</span>(ar_orders):</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>    fitted_models[ar] <span class="op">=</span> {}</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r, ma <span class="kw">in</span> <span class="bu">enumerate</span>(ma_orders):</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>        ar_model <span class="op">=</span> ARIMA(d, order<span class="op">=</span>(ar, <span class="dv">0</span>, ma))</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>        ar_model_fit <span class="op">=</span> ar_model.fit()</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>        fitted_models[ar][ma] <span class="op">=</span> ar_model_fit</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(d, color<span class="op">=</span>color)</span>
<span id="cb44-28"><a href="#cb44-28" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(ar_model_fit.fittedvalues, color<span class="op">=</span>outcol, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb44-29"><a href="#cb44-29" aria-hidden="true" tabindex="-1"></a>        axes[r,c].set_title(<span class="ss">f'</span><span class="sc">{</span>typ<span class="sc">}</span><span class="ss"> ARMA Model p=</span><span class="sc">{</span>ar<span class="sc">}</span><span class="ss">, q=</span><span class="sc">{</span>ma<span class="sc">}</span><span class="ss">'</span>) <span class="co">#, AIC={ar_model_fit.aic}, BIC={ar_model_fit.bic}')</span></span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a>        axes[r,c].text(<span class="fl">0.02</span>,<span class="fl">0.98</span>, <span class="ss">f'AIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>aic<span class="sc">}</span><span class="ss">, BIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>bic<span class="sc">}</span><span class="ss">'</span>, ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'top'</span>, transform<span class="op">=</span>axes[r,c].transAxes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these plots we can conclude that the <span class="math inline">\(p=1\)</span>, and <span class="math inline">\(q=1\)</span> model has both the lowest AIC and BIC, likely drawing the same conclusions as the <code>dns</code> blocking model. It is likely that the data for this test depends only on its nearest neighbor in the time series.</p>
<div id="341992e7" class="cell" data-execution_count="41">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>fitted_models[<span class="dv">1</span>][<span class="dv">1</span>].summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="41">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>SARIMAX Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>http-failure</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>365</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>ARIMA(1, 0, 1)</td>
<td data-quarto-table-cell-role="th">Log Likelihood</td>
<td>-1089.778</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 17 Mar 2025</td>
<td data-quarto-table-cell-role="th">AIC</td>
<td>2187.555</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:48:13</td>
<td data-quarto-table-cell-role="th">BIC</td>
<td>2203.155</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sample:</td>
<td>01-01-2022</td>
<td data-quarto-table-cell-role="th">HQIC</td>
<td>2193.755</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td>- 12-31-2022</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>opg</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>3.2185</td>
<td>1.488</td>
<td>2.163</td>
<td>0.031</td>
<td>0.302</td>
<td>6.135</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L1</td>
<td>0.9166</td>
<td>0.029</td>
<td>31.530</td>
<td>0.000</td>
<td>0.860</td>
<td>0.974</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ma.L1</td>
<td>-0.7067</td>
<td>0.037</td>
<td>-19.358</td>
<td>0.000</td>
<td>-0.778</td>
<td>-0.635</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sigma2</td>
<td>22.9265</td>
<td>0.742</td>
<td>30.893</td>
<td>0.000</td>
<td>21.472</td>
<td>24.381</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Ljung-Box (L1) (Q):</td>
<td>0.04</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>7327.69</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Q):</td>
<td>0.85</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Heteroskedasticity (H):</td>
<td>1.47</td>
<td data-quarto-table-cell-role="th">Skew:</td>
<td>3.47</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(H) (two-sided):</td>
<td>0.03</td>
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>23.83</td>
</tr>
</tbody>
</table>
<br><br>Warnings:<br>[1] Covariance matrix calculated using the outer product of gradients (complex-step).
</div>
</div>
<p>Finally, for the <code>tcp_ip</code> blocking models, we have to use an integration term <span class="math inline">\(d=1\)</span> due to the fact that it is not unlikely that the 0th order data is non-stationary. Therefore the integration term set to 1 will consider the first order difference to be the stationary set. There are peaks in the partial autocorrelation plots at 1, 2, 8, and 10 which we test with the AR terms of the model.</p>
<div id="5aa01a80" class="cell" data-execution_count="42">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try out different ARMA terms</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ar_orders <span class="op">=</span> [<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">10</span>]</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>ma_orders <span class="op">=</span> [<span class="dv">0</span>,<span class="dv">1</span>]</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Type and color</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>typ <span class="op">=</span> tdf.columns[i]</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> palette[i]</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>outcol <span class="op">=</span> palette[<span class="bu">len</span>(tdf.columns)<span class="op">+</span><span class="dv">2</span>]</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> tdf[typ]</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot options</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> [<span class="dv">8</span><span class="op">*</span><span class="bu">len</span>(ar_orders), <span class="dv">4</span><span class="op">*</span><span class="bu">len</span>(ma_orders)]</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through all models</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>fitted_models <span class="op">=</span> {}</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.figure(figsize=(12*len(ma_orders), 4*len(ar_orders)))</span></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="bu">len</span>(ma_orders), <span class="bu">len</span>(ar_orders), sharex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c, ar <span class="kw">in</span> <span class="bu">enumerate</span>(ar_orders):</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>    fitted_models[ar] <span class="op">=</span> {}</span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r, ma <span class="kw">in</span> <span class="bu">enumerate</span>(ma_orders):</span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a>        ar_model <span class="op">=</span> ARIMA(d, order<span class="op">=</span>(ar, <span class="dv">1</span>, ma))</span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>        ar_model_fit <span class="op">=</span> ar_model.fit()</span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a>        fitted_models[ar][ma] <span class="op">=</span> ar_model_fit</span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(d, color<span class="op">=</span>color)</span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a>        axes[r,c].plot(ar_model_fit.fittedvalues, color<span class="op">=</span>outcol, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a>        axes[r,c].set_title(<span class="ss">f'</span><span class="sc">{</span>typ<span class="sc">}</span><span class="ss"> ARIMA Model p=</span><span class="sc">{</span>ar<span class="sc">}</span><span class="ss">, q=</span><span class="sc">{</span>ma<span class="sc">}</span><span class="ss">'</span>) <span class="co">#, AIC={ar_model_fit.aic}, BIC={ar_model_fit.bic}')</span></span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a>        axes[r,c].text(<span class="fl">0.02</span>,<span class="fl">0.98</span>, <span class="ss">f'AIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>aic<span class="sc">}</span><span class="ss">, BIC=</span><span class="sc">{</span>ar_model_fit<span class="sc">.</span>bic<span class="sc">}</span><span class="ss">'</span>, ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'top'</span>, transform<span class="op">=</span>axes[r,c].transAxes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="FullAnalysis_JN_files/figure-html/cell-43-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From these plots we can conclude that the best model is where <span class="math inline">\(p=10\)</span> and <span class="math inline">\(q=1\)</span> since this is where both AIC and BIC are the lowest. This model captures more of the chaotic nature during the anomalous spike event with its higher order terms, but also overshoots those values in order to fit them.</p>
<div id="665c9bdd" class="cell" data-execution_count="43">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fitted_models[<span class="dv">10</span>][<span class="dv">1</span>].summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="43">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>SARIMAX Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>tcp_ip</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>365</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>ARIMA(10, 1, 1)</td>
<td data-quarto-table-cell-role="th">Log Likelihood</td>
<td>-1988.374</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 17 Mar 2025</td>
<td data-quarto-table-cell-role="th">AIC</td>
<td>4000.748</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:48:15</td>
<td data-quarto-table-cell-role="th">BIC</td>
<td>4047.514</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Sample:</td>
<td>01-01-2022</td>
<td data-quarto-table-cell-role="th">HQIC</td>
<td>4019.335</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th"></td>
<td>- 12-31-2022</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>opg</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L1</td>
<td>0.5196</td>
<td>0.037</td>
<td>14.025</td>
<td>0.000</td>
<td>0.447</td>
<td>0.592</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L2</td>
<td>-0.1701</td>
<td>0.023</td>
<td>-7.425</td>
<td>0.000</td>
<td>-0.215</td>
<td>-0.125</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L3</td>
<td>0.2824</td>
<td>0.033</td>
<td>8.519</td>
<td>0.000</td>
<td>0.217</td>
<td>0.347</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L4</td>
<td>-0.0470</td>
<td>0.033</td>
<td>-1.427</td>
<td>0.154</td>
<td>-0.112</td>
<td>0.018</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L5</td>
<td>0.1842</td>
<td>0.032</td>
<td>5.723</td>
<td>0.000</td>
<td>0.121</td>
<td>0.247</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L6</td>
<td>0.0578</td>
<td>0.033</td>
<td>1.728</td>
<td>0.084</td>
<td>-0.008</td>
<td>0.123</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L7</td>
<td>0.0662</td>
<td>0.043</td>
<td>1.537</td>
<td>0.124</td>
<td>-0.018</td>
<td>0.151</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L8</td>
<td>0.0756</td>
<td>0.035</td>
<td>2.137</td>
<td>0.033</td>
<td>0.006</td>
<td>0.145</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ar.L9</td>
<td>-0.0832</td>
<td>0.040</td>
<td>-2.070</td>
<td>0.038</td>
<td>-0.162</td>
<td>-0.004</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ar.L10</td>
<td>-0.2875</td>
<td>0.025</td>
<td>-11.326</td>
<td>0.000</td>
<td>-0.337</td>
<td>-0.238</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ma.L1</td>
<td>-0.9076</td>
<td>0.027</td>
<td>-33.570</td>
<td>0.000</td>
<td>-0.961</td>
<td>-0.855</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sigma2</td>
<td>3232.7776</td>
<td>91.481</td>
<td>35.338</td>
<td>0.000</td>
<td>3053.478</td>
<td>3412.077</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Ljung-Box (L1) (Q):</td>
<td>0.19</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>3823.43</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Q):</td>
<td>0.66</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Heteroskedasticity (H):</td>
<td>0.00</td>
<td data-quarto-table-cell-role="th">Skew:</td>
<td>1.18</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(H) (two-sided):</td>
<td>0.00</td>
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>18.70</td>
</tr>
</tbody>
</table>
<br><br>Warnings:<br>[1] Covariance matrix calculated using the outer product of gradients (complex-step).
</div>
</div>
</section>
</section>
<section id="results-analysis-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="results-analysis-and-discussion">Results, Analysis, and Discussion</h2>
<p>The most interesting results that were discovered throughout this project were done through exploratory data analysis and then testing our assumptions of the data through modeling and statistical testing. Our intial assumptions about what might seem interesting were actually completely wrong after seeing the Croatia 2022 data which became an unexpected central focus.</p>
<section id="anomalies" class="level3">
<h3 class="anchored" data-anchor-id="anomalies">Anomalies</h3>
<p>From our anomaly detection method, we determined 3 unique regions of interest with different distributions of blocking events in each. Through the two sample Z-Test within and outside of these ranges we can say that:</p>
<ul>
<li>All blocking events in region <strong>(a)</strong> likely do not have the same mean as outside of the region</li>
<li><code>http_diff</code> and <code>tcp_ip</code> events within <strong>(b)</strong> are likely to not have the same mean as outside of this range, but nothing can be said confidently of the other two methods</li>
<li><code>http_diff</code> and <code>dns</code> events within <strong>(c)</strong> are likely to not have the same mean as outside of this range, but nothing can be said confidently of the other two methods</li>
</ul>
<p>We recognize that there is a caveat to running the two sample Z-Test on our data, since the data is not likely completely independent and normally distributed. However what we can conclude is that through the later plots of autocorrelations, most of the blocking methods lose self-similarity after a period of <span class="math inline">\(7\)</span> days or so, which means that localized events in time periods longer than this are likely to be able to have their means tested against each other. We also are testing sample sizes greater than <span class="math inline">\(30\)</span> datapoints which makes it more likely for the data to be normally distributed through the Central Limit Theorem, especially since there is very little to no seasonality observed in the data itself. If there were more regular spikes at intervals in the partial correlation plots for each of the blocking types, it would be more likely that we couldn’t conclude much about the Z-Tests, however it does provide an interesting point of reference for further exploration.</p>
</section>
<section id="model-analysis" class="level3">
<h3 class="anchored" data-anchor-id="model-analysis">Model Analysis</h3>
<p>From our models, we can make the conclusion that the <code>tcp_ip</code> blocking events are most likely non-stationary in the time series data. This means that the <code>tcp_ip</code> blocking events likely are a more complex function of time, and specifically a 1st order function. This is evidenced by the fact that it reaches stationarity in the first order differential.</p>
<p>After running different combinations of ARMA and ARIMA models, we have determined the following characteristics of the different blocking events through the models that produced the lowest AIC and BIC values:</p>
<ul>
<li><code>dns</code> - Likely the first order autoregression and first order moving average are decent predictors of future behavior, meaning that one step in the past is likely to vary in the same direction as the future time step.</li>
<li><code>http_diff</code> - Likely there are 3rd to 6th order terms that allow predicting future behavior fairly well, and including a moving average also further improves model accuracy.</li>
<li><code>http_fail</code> - As with <code>dns</code>, likely the first order autoregression and first order moving average are decent predictors of future behavior.</li>
<li><code>tcp_ip</code> - There is much more chaotic and higher order behavior occurring due to the fact that the <span class="math inline">\(p=10\)</span> model performed the best. The anomalous nature of the region of interest suggests that this is a much more interesting and dynamic blocking event type.</li>
</ul>
<p>From our models, we can characterize these blocking event types, however it would be more interesting to explore the inter-country relationships using one model to try to test the behavior of another country’s data. This would likely not produce super accurate results, but might indicate whether there is any predictive power from what we see in Croatia in 2022 on another country with similar or differing censorship activity. This would require that we collect even more data from a larger pool of date ranges and countries which was just not feasible for the scope of this project.</p>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>In order to make full conclusions about the anomalous behavior of Croatia during 2022, we would need to have a larger context of potential behaviors, specifically around <code>tcp_ip</code> blocking events in different countries. Just looking at Belarus and Nepal during those time periods was at least a glimpse of the distributions of a country with known censorship history, and a country with potential censorship, however an extended series of date ranges would provide additional insights.</p>
<p>There is just not enough data to make a solid conclusion about what exactly is happening in the anomalous regions we detected, but they are at least an interesting set of targets for further analysis.</p>
<p>Additionally, we would like to reach out to OONI to provide them with these findings and get their opinions on what could be happening in the data to avoid any false accusations.</p>
</section>
</section>
<section id="impact" class="level2">
<h2 class="anchored" data-anchor-id="impact">Impact</h2>
<p>We believe this data analysis to have significant impact. Censorship is dangerous, and with the political climate of the world heading in the direction it currently is, we need to fight to prevent censorship at any turn. This style of data analysis is important in that fight. To this day, no one has been able to create a perfect automated censorship detection system. Most systems have to run some form of detection set up to never have false negatives. The system then sets up an alarm which will cause an expert to analyze the data to determine whether real censorship is taking place or not.</p>
<p>If our analysis is correct, there is a non-zero chance of a major temporal censorship event occuring in an open country which has not yet been reported on. This would have major implications politically. Because of this significance, we cannot make any accusations without following up. One of our group members is in contact with OONI for other research purposes. He has been in communication with the CTO of OONI for other projects. He will ask the CTO about this later. If our analysis is correct, this is a major event that needs to be made public.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>